// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWqVqBhgh7CZ6p0Ut5Wy_kBbJ470L_LKQ',
    appId: '1:684708293678:web:3bcd015b038af948b1c3bf',
    messagingSenderId: '684708293678',
    projectId: 'drdo-leaf',
    authDomain: 'drdo-leaf.firebaseapp.com',
    storageBucket: 'drdo-leaf.appspot.com',
    measurementId: 'G-7VYE3RJT75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtSWCurCRw0tyhD-kQ9jWVjfBnkRJboAY',
    appId: '1:684708293678:android:33ef607f6bfc8e3ab1c3bf',
    messagingSenderId: '684708293678',
    projectId: 'drdo-leaf',
    storageBucket: 'drdo-leaf.appspot.com',
  );
}
